#Numpy

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\python\python39\python.exe -m pip install --upgrade pip' command.


In [3]:
import numpy as np
import math

In [4]:
a = np.array([1,2,3]) #Creates arrays
print(a)

[1 2 3]


In [6]:
b = np.array([[1,2,3], [4,5,6]]) #list of list in an array
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
b.shape #check dimensions

(2, 3)

In [9]:
a.dtype #checks type

dtype('int32')

In [13]:
c = np.array([2.2, 1.5, 1.1]) #Output just the name type
c.dtype.name

'float64'

In [16]:
d = np. zeros((2,3)) #Creates arrays with zeros or ones
e = np.ones((2,4))
print(d)
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [17]:
np.random.rand(2,3) #random numbers

array([[0.45002883, 0.47244688, 0.57044389],
       [0.86185726, 0.38114903, 0.64834949]])

In [19]:
f = np.arange(10,40,2) #arrays from 10 to 40 every 2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [20]:
np.linspace(0,2,15) #Gets 15 numbers within 0 and 2

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

#Array Operations

In [22]:
a = np.array([10, 20, 30, 40])
b = np.array([1,2,3,4])

c = a -b
print(c)

d= a *b
print(d)

[ 9 18 27 36]
[ 10  40  90 160]


In [25]:
farenheit = np.array([-10, 0, 10, 20, 30, 40, 50, 60, 70])

celcius = (farenheit - 31) * (5/9)
celcius

array([-22.77777778, -17.22222222, -11.66666667,  -6.11111111,
        -0.55555556,   5.        ,  10.55555556,  16.11111111,
        21.66666667])

In [26]:
celcius > 0 #Gets True if its higher than 0

array([False, False, False, False, False,  True,  True,  True,  True])

In [28]:
celcius%5 == 0

array([False, False, False, False, False,  True, False, False, False])

In [31]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])
print(A*B)
print(A@B) #Matrix product

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [32]:
A.shape

(2, 2)

In [33]:
a1 = np.array([[1,2,3], [4,5,6]])
print(a1.dtype)
a2 = np.array([[3.4, 2.2, 7.5], [8.5, 2.4, 5.3]])
print(a2.dtype)

int32
float64


In [34]:
a3 = a1 + a2
a3

array([[ 4.4,  4.2, 10.5],
       [12.5,  7.4, 11.3]])

In [36]:
print(a3.sum()) #agreagtion functions
print(a3.max())
print(a3.min())
print(a3.mean())

50.3
12.5
4.2
8.383333333333333


In [42]:
b = np.arange(1,16,1)  #reorder arrays
print(b)
c = b.reshape(3,5)
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
a[3]

4

In [4]:
b = np.array([[1,2], [3,4], [5,6]])
b[1][1]

4

In [5]:
b[1,1] #both correct wways to index

4

In [10]:
np.array([b[0,1], b[1,1], b[2,1]]) #Get diferent indexes into a new array

array([2, 4, 6])

In [9]:
print(b[[0,1,2], [1,1,1]]) #alternative way: first list looks for the "set", 
                            #second one search within the set

[2 4 6]


In [11]:
a > 3

array([False, False, False,  True,  True])

In [12]:
print(a[a > 3]) #Gets the real values of the above

[4 5]


In [20]:
z = np.array([1,2,3,4,5,6,7,8,9])
print(z[:3]) #start to index
print(z[3:7]) #index to index
print(z[5:]) #index to end

[1 2 3]
[4 5 6 7]
[6 7 8 9]


In [20]:
import numpy as np
y = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
y

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
print(y[2])
print(y[2,1])

[ 9 10 11 12]
10


In [24]:
print(y[:, 1]) #Gets all rows of column 1
print("1 to 3 for slicing: \n", y[:, 1:3]) #Gets all rows from colum 1 to 3
print(y[:, [1,-1]]) #Select specific columns

[ 2  6 10]
1 to 3 for slicing: 
 [[ 2  3]
 [ 6  7]
 [10 11]]
[[ 2  4]
 [ 6  8]
 [10 12]]


In [33]:
print(y)
print(y[0].mean()) #Gets mean of row one
print(y[:,-1].mean()) #gets mean of last column
print(y[:, [1,-1]].mean()) #gets the mean between column two and last one

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
2.5
8.0
7.0


In [9]:
sub_array = y[:2, 1:3]
print(sub_array)
print("sub array index [0,0] value before change:", sub_array[0,0])

[[2 3]
 [6 7]]
sub array index [0,0] value before change: 2


In [11]:
sub_array[0,0] = 50
print("sub array index [0,0] value after change:", sub_array[0,0])
print("original array index [0,1] value after change:", y[0,1])

sub array index [0,0] value after change: 50
original array index [0,1] value after change: 50


In [34]:
'C:\Users\Propietario\Desktop\Jupyter\Intro\Datasets\Admission_Predict.csv'

SyntaxError: unexpected character after line continuation character (<ipython-input-34-3d96cafce7a5>, line 1)

In [35]:
graduate_admission = np.genfromtxt('C:\Users\Propietario\Desktop\Jupyter\Intro\Datasets\Admission_Predict.csv', dtype=None, delimiter=',', skip_header=1,
                                   names=('Serial No','GRE Score', 'TOEFL Score', 'University Rating', 'SOP',
                                          'LOR','CGPA','Research', 'Chance of Admit'))
graduate_admission

SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape (<ipython-input-35-64df43fe5842>, line 1)